name: disaster_safety
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  geoflutterfire_plus: ^0.0.20
  geolocator: ^11.0.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  image: ^4.0.17
  image_picker: ^1.0.4
  mockito: ^5.4.4
  path: ^1.8.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
